# render.yaml - FINAL BLUEPRINT WITH EXPLICIT FREE TIER

services:
  # A Web Service for the Laravel Application using Docker
  - type: web
    name: nexuscomply-app 
    env: docker 
    plan: free # <-- IMPORTANT: This guarantees the free web service plan

    # Your repository details
    repo: https://github.com/Wernjie0713/NexusComply.git
    branch: main
    
    # Docker build settings
    rootDir: app_laravel
    dockerfilePath: ./Dockerfile
    
    # Health Check
    healthCheckPath: /api/health

    # Environment Variables
    envVars:
      - key: APP_URL
        generateValue: true

      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_DRIVER
        value: redis 
      - key: SESSION_DRIVER
        value: redis
      # Tell Laravel how to connect to our Redis service (below)
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexuscomply-cache
          property: connectionString

  # The free Redis instance for Caching and Sessions
  - type: redis
    name: nexuscomply-cache
    plan: free # <-- IMPORTANT: This guarantees the free Redis plan
    ipAllowList: [] # Allows access only from your other Render services