# render.yaml - CORRECTED BLUEPRINT FOR NEXUSCOMPLY

services:
  # A Web Service for the Laravel Application using Docker
  - type: web
    name: nexuscomply-app # You can keep this name
    env: docker # This correctly sets the environment to Docker
    
    # Your repository details
    repo: https://github.com/Wernjie0713/NexusComply.git # This should match your repo
    branch: main # Or master
    
    # Docker build settings
    rootDir: app_laravel
    dockerfilePath: ./Dockerfile
    
    # Health Check to know when the app is live
    healthCheckPath: /api/health

    # Environment Variables
    envVars:
      # --- FIX #1: Use generateValue for APP_URL ---
      - key: APP_URL
        generateValue: true # This tells Render to automatically assign its public URL

      # --- Non-secret variables ---
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: LOG_CHANNEL
        value: stderr
      # Use Redis for caching and sessions for better performance
      - key: CACHE_DRIVER
        value: redis
      - key: SESSION_DRIVER
        value: redis
      # Tell Laravel how to connect to our Redis service (below)
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexuscomply-cache # Must match the name of the redis service
          property: connectionString

  # The free Redis instance for Caching and Sessions
  - type: redis
    name: nexuscomply-cache
    # --- FIX #2: Add the required ipAllowList ---
    ipAllowList: [] # An empty list securely allows access ONLY from your other Render services